name: Quality checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  quality-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm ci

      - name: Check formatting
        run: npm run format:check

      # - name: Lint code
      # run: npm run lint

      - name: Validate types
        run: npm run type-check
